#端口号
server:
  port: 9099
#app相关信息
app:
  urlValue: 192.168.2.15:${server.port}
  url: http://${app.urlValue}
  name: Joyce
  version: 1.0
#数据库数据源相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
  #静态资源路径配置
  web:
    resources:
      static-locations: classpath:static/,file:${file.upload.path}
  #thymeleaf的配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  #热部署配置
  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: src/main
  #邮件验证开启
  mail:
    host: smtp.qq.com
    #发送者邮件
    username: 1154517070@qq.com
    # 生成的密匙
    password: cbeilolivceihghd
    default-encoding: UTF-8
    from: 1154517070@qq.com
    emailPassword: hj951206
  mvc:
    hiddenmethod:
      filter:
        enabled: false
    static-path-pattern: /static/**
  servlet:
    multipart:
      #最大的上传数据
      max-file-size: 5MB
  #jpa配置
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      # 未删除
      logic-not-delete-value: 0
      # 已删除
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#文件路径上传路径
file:
  config:
    path: D://${app.name}/files/config/
  upload:
    access: /img/photo/${random.int}/
    relative: ${file.upload.access}**
    path: D://${app.name}/upload/images/



#监听获得当前登录者
context:
  initializer:
#    classes: com.moon.joyce.listeners.JoyceApplicationContextInitializer.java
